ContainRs-main/ContainRs.WebApp/Models/Cliente.cs
namespace ContainRs.WebApp.Models;

public class Cliente
{
    private Cliente() { } // EF Core
    public Cliente(string nome, Email email, string cPF)
    {
        Nome = nome;
        Email = email;
        CPF = cPF;
    }

    public Guid Id { get; set; }
    public string Nome { get; private set; }
    public Email Email { get; private set; }
    public string CPF { get; private set; }
    public string? Celular { get; set; }
    public string? CEP { get; set; }
    public string? Rua { get; set; }
    public string? Numero { get; set; }
    public string? Complemento { get; set; }
    public string? Bairro { get; set; }
    public string? Municipio { get; set; }
    public string? Cidade { get; set; }
    public string? Estado { get; set; }
}

ContainRs-main/ContainRs.WebApp/Models/ClienteResponse.cs
namespace ContainRs.WebApp.Models
{
    public record ClienteResponse(string Id, string Nome, string Email);
}

ContainRs-main/ContainRs.WebApp/Models/Email.cs
using System.Text.RegularExpressions;

namespace ContainRs.WebApp.Models
{
    public class Email
    {

        private static readonly Regex EmailRegex = new Regex(
            @"^[^@\s]+@[^@\s]+\.[^@\s]+$",
            RegexOptions.Compiled | RegexOptions.IgnoreCase);

        public Email(string value)
        {
            if (!EmailRegex.IsMatch(value))
            {
                throw new ArgumentException("E-mail inválido.");
            }
            Value = value;
        }

        public string Value { get; }
    }
}

ContainRs-main/ContainRs.WebApp/Models/ErrorViewModel.cs
namespace ContainRs.WebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ContainRs-main/ContainRs.WebApp/Models/RegistroViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ContainRs.WebApp.Models;

public class RegistroViewModel
{
    [Display(Name ="Nome (*)", Prompt = "Digite seu nome completo.")]
    [Required(ErrorMessage = "Campo obrigatório.")]
    public string Nome { get; set; }

    [Display(Name = "E-mail (*)", Prompt = "Digite seu melhor e-mail.")]
    [Required(ErrorMessage = "Campo obrigatório.")]
    [EmailAddress(ErrorMessage = "E-mail inválido.")]
    public string Email { get; set; }

    [Display(Name = "CPF (*)", Prompt = "000.000.000-00")]
    [Required(ErrorMessage = "Campo obrigatório.")]
    public string CPF { get; set; }
    [Display(Prompt = "(00) 00000-0000")]
    public string? Celular { get; set; }
    [Display(Prompt = "00.000-000")]
    public string? CEP { get; set; }
    public string? Rua { get; set; }
    public string? Numero { get; set; }
    public string? Complemento { get; set; }
    public string? Bairro { get; set; }
    public string? Municipio { get; set; }
    public string? Estado { get; set; }
    public DateTime Nascimento { get; set; }
}

ContainRs-main/ContainRs.WebApp/Controllers/ApiClientesController.cs
using ContainRs.Application.UseCases;
using ContainRs.Domain.Models;
using ContainRs.WebApp.Data;
using ContainRs.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace ContainRs.WebApp.Controllers
{
    [ApiController]
    [Route("api/clientes")]
    public class ApiClientesController : ControllerBase
    {
        private readonly AppDbContext _context;

        public ApiClientesController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> GetAsync(string? estado)
        {
            var useCase = new ConsultarClientes(UfStringConverter.From(estado), _context);
            var clientes = await useCase.ExecutarAsync();
            return Ok(clientes.Select(c => new ClienteResponse(c.Id.ToString(), c.Nome, c.Email.Value)));
        }
    }
}

ContainRs-main/ContainRs.WebApp/Controllers/ApiRegistroController.cs
using ContainRs.WebApp.Data;
using ContainRs.WebApp.Models;
using ContainRs.Domain.Models;
using ContainRs.Application.UseCases;
using Microsoft.AspNetCore.Mvc;

namespace ContainRs.WebApp.Controllers
{
    [ApiController]
    [Route("api/registros")]
    public class ApiRegistroController : ControllerBase
    {
        private readonly AppDbContext context;

        public ApiRegistroController(AppDbContext context)
        {
            this.context = context;
        }

        [HttpPost]
        public async Task<IActionResult> CreatAsync(RegistroViewModel request)
        {

            var useCase = new RegistrarCliente
                (
                    context,
                    request.Nome,
                    new Email(request.Email),
                    request.CPF,
                    request.Celular,
                    request.CEP,
                    request.Rua,
                    request.Numero,
                    request.Complemento,
                    request.Bairro,
                    request.Municipio,
                    UfStringConverter.From(request.Estado)
                );


            await useCase.ExecutarAsync();

            return  Ok();
        }
    }
}

ContainRs-main/ContainRs.WebApp/Controllers/CepController.cs
using ContainRs.WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace ContainRs.WebApp.Controllers;
public class CepController : Controller
{
    private readonly IViaCepService _cepService;

    public CepController(IViaCepService cepService)
    {
        _cepService = cepService;
    }

    public async Task<IActionResult> Consultar(string cep)
    {
        // consultar o CEP usando Refit
        var response = await _cepService.ConsultarAsync(cep);

        if (response.StatusCode != System.Net.HttpStatusCode.OK)
        {
            return Json(new { Error = "CEP não encontrado" });
        }

        return Json(new 
        { 
            CEP = response.Content!.CEP,
            Rua = response.Content.Logradouro,
            Bairro = response.Content.Bairro,
            Municipio = response.Content.Localidade,
            Estado = response.Content.UF
        });
    }
}

ContainRs-main/ContainRs.WebApp/Controllers/HomeController.cs
using ContainRs.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ContainRs.WebApp.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ContainRs-main/ContainRs.WebApp/Controllers/RegistroController.cs
using ContainRs.WebApp.Data;
using ContainRs.WebApp.Models;
using ContainRs.Domain.Models;
using ContainRs.Application.UseCases;
using Microsoft.AspNetCore.Mvc;

namespace ContainRs.WebApp.Controllers;

public class RegistroController : Controller
{
    private readonly AppDbContext context;

    public RegistroController(AppDbContext context)
    {
        this.context = context;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Sucesso() => View();

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateAsync(RegistroViewModel form)
    {
        if (!ModelState.IsValid) return View("Index", form);
        var idade = DateTime.Today.Year - form.Nascimento.Year;
        if (idade < 18)
        {
            ModelState.AddModelError("Nascimento", "Cliente deve ter 18 anos ou mais para se cadastrar.");
            return View("Index", form);
        }

        var useCase = new RegistrarCliente
        (
            context,
            form.Nome,
            new Email(form.Email),
            form.CPF,
            form.Celular,
            form.CEP,
            form.Rua,
            form.Numero,
            form.Complemento,
            form.Bairro,
            form.Municipio,
            UfStringConverter.From(form.Estado)
        );

        await useCase.ExecutarAsync();

        return RedirectToAction("Sucesso");
    }
}

ContainRs-main/ContainRs.WebApp/Views/Home/Index).cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ContainRs-main/ContainRs.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ContainRs-main/ContainRs.WebApp/Views/Registro/Sucesso.cshtml
@{
}

<div class="rounded-1 bg-white animate__animated animate__tada pt-5 pb-2 px-3">
    <h1>
        Registro efetuado com sucesso!
        <i class="bi bi-hand-thumbs-up-fill text-success"></i>
    </h1>
    <p class="mt-4 text-center">
        <a asp-controller="Registro" asp-action="Index" class="btn btn-lg btn-outline-success">Novo Registro</a>
    </p>
</div>

ContainRs-main/ContainRs.WebApp/Views/Shared/Index.cshtml
@model RegistroViewModel

@{
    ViewData["Title"] = "Registro";
    var hasValidationErrors = ViewData.ModelState.ErrorCount > 0;
}

<form class="row bg-lightgray pt-5 pb-4 px-3 rounded w-50" role="form" asp-action="Create" asp-antiforgery="true">

    <div class="d-flex flex-row justify-content-between align-items-end">
        <h2>
            <i class="bi bi-person-fill"></i>
            Registro
        </h2>
        <img width="100px" src="~/images/containrs_logo.png" />
    </div>

    <div class="form-group col-12 mt-2">
        <label class="form-label" asp-for="Nome"></label>
        <input class="form-control" asp-for="Nome"/>
        <span class="is-invalid text-danger small" asp-validation-for="Nome"></span>
    </div>

    <div class="form-group col-6 mt-2">
        <label class="form-label" asp-for="Email"></label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger small" asp-validation-for="Email"></span>
    </div>

    <div class="form-group col-3 mt-2">
        <label class="form-label" asp-for="CPF"></label>
        <input class="form-control" asp-for="CPF" />
        <span class="text-danger small" asp-validation-for="Email"></span>
    </div>

    <div class="form-group col-3 mt-2">
        <label class="form-label" asp-for="Celular"></label>
        <input class="form-control" asp-for="Celular" />
    </div>

    <div class="form-group col-3 mt-2">
        <label class="form-label" asp-for="CEP"></label>
        <input class="form-control" asp-for="CEP" />
    </div>

    <div class="form-group col-3 mt-2">
        <label class="form-label" asp-for="Nascimento"></label>
        <input class="form-control" asp-for="Nascimento" />
        <span asp-validation-for="Nascimento" class="text-danger small"></span>
    </div>

    <div class="form-group col-4 mt-2">
        <label class="form-label" asp-for="Rua"></label>
        <input class="form-control" asp-for="Rua" />
    </div>

    <div class="form-group col-2 mt-2">
        <label class="form-label" asp-for="Numero"></label>
        <input class="form-control" asp-for="Numero" />
    </div>

    <div class="form-group col-3 mt-2">
        <label class="form-label" asp-for="Complemento"></label>
        <input class="form-control" asp-for="Complemento" />
    </div>

    <div class="form-group col-5 mt-2">
        <label class="form-label" asp-for="Bairro"></label>
        <input class="form-control" asp-for="Bairro" />
    </div>

    <div class="form-group col-5 mt-2">
        <label class="form-label" asp-for="Municipio"></label>
        <input class="form-control" asp-for="Municipio" />
    </div>

    <div class="form-group col-2 mt-2">
        <label class="form-label" asp-for="Estado"></label>
        <input class="form-control" asp-for="Estado" />
    </div>

    <div class="form-group col-12 mt-3">
        <button class="btn btn-lg btn-color1 mt-3">Registrar</button>
    </div>

</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script type="text/javascript">
        $(document).ready(function () {

            $('#CPF').mask('000.000.000-00');
            $('#Celular').mask('(00) 00000-0000');
            $('#CEP').mask('00.000-000');

            let debounceTimeout;

            $('#CEP').on('input', function () {
                clearTimeout(debounceTimeout); 
                var query = $(this).cleanVal();
                console.log(query);

                debounceTimeout = setTimeout(function () {
                    if (query.length == 8) { 
                        $.ajax({
                            url: '/CEP/Consultar', 
                            data: { cep: query },
                            success: function (data) {
                                console.log(data);
                                $('#Rua').val(data.rua);
                                $('#Bairro').val(data.bairro);
                                $('#Municipio').val(data.municipio);
                                $('#Estado').val(data.estado);
                            },
                            error: function () {
                                console.log('Erro na busca.');
                            }
                        });
                    } else {

                        // Limpar endereço
                    }
                }, 300); 
            });

        });
    </script>
}

ContainRs-main/ContainRs.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContainRs.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContainRs.WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
</head>
<body class="d-flex flex-column justify-content-center align-items-center">
    
    @RenderBody()
        
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>